# Generated by Django 4.1.7 on 2023-04-17 17:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0008_alter_model_id_marque'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('gmail', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('cin', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('prenom', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=20)),
                ('sexe', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('telephone', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('Reservation_Date', models.DateField(default=datetime.date.today)),
                ('ModelName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.model')),
            ],
        ),
    ]
