# Generated by Django 4.1.7 on 2023-04-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='prenom',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
