# Generated by Django 4.1.7 on 2023-04-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_client_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='id_client',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='cin',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='prenom',
            field=models.CharField(max_length=20),
        ),
    ]
