# Generated by Django 4.1.7 on 2023-04-03 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id_marque', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id_model', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=20)),
                ('annee', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.FileField(upload_to='photos/%y/%m/%d')),
                ('image1', models.FileField(blank=True, null=True, upload_to='photos/%y/%m/%d')),
                ('image2', models.FileField(blank=True, null=True, upload_to='photos/%y/%m/%d')),
                ('image3', models.FileField(blank=True, null=True, upload_to='photos/%y/%m/%d')),
                ('content', models.TextField(blank=True, null=True)),
                ('puissance', models.IntegerField()),
                ('energie', models.CharField(choices=[('Essence', 'essence'), ('Diesel', 'diesel')], max_length=20)),
                ('nbr_plc', models.IntegerField()),
                ('vitesse', models.CharField(choices=[('Manual', 'manual'), ('Automatic', 'automatic')], max_length=20)),
                ('id_marque', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='products.marque')),
            ],
        ),
    ]
