# Generated by Django 4.1.7 on 2023-04-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='speed',
            field=models.IntegerField(default=0),
        ),
    ]
