# Generated by Django 4.1.7 on 2023-04-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_model_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='speed',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
