# Generated by Django 4.1.7 on 2023-04-10 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_model_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='id_marque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marque', to='products.marque'),
        ),
        migrations.AlterField(
            model_name='model',
            name='speed',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
