# Generated by Django 4.1.7 on 2023-04-12 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_model_id_marque_alter_model_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='marque',
            name='logo',
            field=models.FileField(default=0, upload_to='photos/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='model',
            name='id_marque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='products.marque'),
        ),
    ]
