# Generated by Django 4.1.7 on 2023-04-12 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_marque_logo_alter_model_id_marque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marque',
            name='logo',
        ),
    ]
